### ISSUE TITLE
Good project!

### ISSUE THREAD

**Issue by mahimai-raja** [shwetabarua/Applied-Data-Science-Capstone#1]
Hey! I am reviewing your project and your project works are really awesome. Keep doing good, and Have a successful year ahead.

**Comment by mahimai-raja** [comment]
Your efforts are really great and I would appreciate you Shwetabarua, A suggestion - for EDA with SQL, You can directly use  SQL commands in jupyter-notebook by adding your credentials of db2 and using SQL as a prefix in every commands just give it a try. Moreover, your overall project is really great and you have done a great job. Your project work is fascinating and would like to connect with you for feature projects. Now I am rewarding you full marks for your accomplishments.

**Comment by shwetabarua** [comment]
Thank you so much for your feedback. I really appreciate the details you shared with me about the areas where I can improve. I appreciate your guidance and hope you have an amazing and successful year ahead as well.
